<a href="https://colab.research.google.com/github/steven202/takehomeexam3/blob/master/exam3_question1_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from tensorflow.python.keras.layers import Dense, Activation
from tensorflow.python.keras import Sequential
from sklearn.datasets import make_blobs
from tensorflow.python.keras.datasets import mnist
from tensorflow.python.keras.utils import np_utils
from tensorflow.python.keras.optimizers import SGD, Adam, RMSprop
import numpy as np
from tensorflow.python.keras import initializers
from tensorflow.python.keras import initializers
from sklearn.model_selection import KFold
# http://cps.ninja/2018/09/21/keras/
# https://blog.csdn.net/marsjhao/article/details/68086225

In [0]:
np.random.seed(1337)  # for reproducibility
classes = 3; 
x_test, y_test = make_blobs(n_samples=10000, centers=classes, n_features=2)
x_train, y_train = make_blobs(n_samples=100, centers=classes, n_features=2)

x_train = x_train.reshape(x_train.shape[0], -1)   # 标准化
x_test = x_test.reshape(x_test.shape[0], -1)
# y_train = np_utils.to_categorical(y_train, num_classes=10)
# y_test = np_utils.to_categorical(y_test, num_classes=10)

In [0]:
def model1(x_train, y_train, x_vali, y_vali,nperceptrons):
  model = Sequential([
    Dense(x_train.shape[0], input_dim=2),
    Activation('relu'),
    Dense(nperceptrons),
    Activation('softmax'),
  ])
  model.compile(loss="categorical_crossentropy", optimizer="SGD", metrics = ['accuracy'])
  # print('Training ------------')
  model.fit(x_train, y_train, epochs=10, batch_size=10,verbose=0)
  # print('\nValidating ------------')
  loss, accuracy = model.evaluate(x_vali, y_vali,verbose=0)
  # print('validate loss: ', loss)
  print('validate accuracy: ', accuracy)
  return accuracy;

In [0]:
def model2(x_train, y_train, x_vali, y_vali,nperceptrons):
  model = Sequential([
    Dense(x_train.shape[0], input_dim=2),
    Activation('sigmoid'),
    Dense(nperceptrons),
    Activation('softmax'),
  ])
  model.compile(loss="categorical_crossentropy", optimizer="SGD", metrics = ['accuracy'])
  # print('Training ------------')
  model.fit(x_train, y_train, epochs=10, batch_size=10,verbose=0)
  # print('\nValidating ------------')
  loss, accuracy = model.evaluate(x_vali, y_vali,verbose=0)
  # print('validate loss: ', loss)
  print('validate accuracy: ', accuracy)
  return accuracy;

In [0]:
#kf = KFold(n_splits=10)
kf = KFold(n_splits=10, random_state=None, shuffle=False)
errors=np.zeros((15,2));

In [26]:
for train_index, vali_index in kf.split(x_train):
  print("TRAIN:", train_index, "VALIDATE:", vali_index)
  X_train, X_vali = x_train[train_index], x_train[vali_index]
  Y_train, Y_vali = y_train[train_index], y_train[vali_index]
  for nperceptrons in range(3,15):
    Y_train2 = np_utils.to_categorical(Y_train, num_classes=nperceptrons)
    Y_vali2 = np_utils.to_categorical(Y_vali, num_classes=nperceptrons)
    errors[nperceptrons-1, 0] += model1(X_train, Y_train2, X_vali, Y_vali2,nperceptrons)
    errors[nperceptrons-1, 1] += model2(X_train, Y_train2, X_vali, Y_vali2,nperceptrons)

TRAIN: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99] VALIDATE: [0 1 2 3 4 5 6 7 8 9]
validate accuracy:  1.0
validate accuracy:  1.0
validate accuracy:  1.0
validate accuracy:  0.8999999761581421
validate accuracy:  1.0
validate accuracy:  0.6000000238418579
validate accuracy:  1.0
validate accuracy:  0.8999999761581421
validate accuracy:  1.0
validate accuracy:  0.800000011920929
validate accuracy:  1.0
validate accuracy:  1.0
validate accuracy:  1.0
validate accuracy:  1.0
validate accuracy:  1.0
validate accuracy:  0.699999988079071
validate accuracy:  1.0
validate accuracy:  1.0
validate accuracy:  1.0
validate accuracy:  0.800000011920929
validate accuracy:  1.0
validate accuracy:  0.699999988079071
validate accuracy:  1.0
validate accuracy:  1.0
TRAIN: [ 

In [27]:
print(errors);
error_set = errors/10;


[[0.         0.        ]
 [0.         0.        ]
 [9.69999999 9.39999998]
 [9.5        8.99999994]
 [9.5        8.89999998]
 [9.59999996 9.29999995]
 [9.59999996 9.09999996]
 [9.59999996 9.29999995]
 [9.69999999 9.5       ]
 [9.5        8.69999999]
 [9.5        8.99999994]
 [9.5        9.19999999]
 [9.69999999 8.79999995]
 [9.59999996 9.5       ]
 [0.         0.        ]]


In [28]:
accu_max = error_set[error_set != 0].max()
print(accu_max)
#https://stackoverflow.com/questions/36363163/find-index-of-min-value-in-a-matrix
ij_max = np.where(error_set == accu_max)
ij_max = tuple([i.item() for i in ij_max])
print(ij_max);

nperceptrons = ij_max[0]+1;
if ij_max[1]==0:
  activate = 'relu';
else:
  activate = 'sigmoid';

0.9699999988079071


ValueError: ignored

In [0]:
def model3(x_train, y_train,nperceptrons):
  model = Sequential([
    Dense(x_train.shape[0], input_dim=2,kernel_initializer='random_uniform',
                bias_initializer='zeros'),
    Activation(activate),
    Dense(nperceptrons,kernel_initializer='random_uniform',
                bias_initializer='zeros'),
    Activation('softmax'),
  ])
  model.compile(loss="categorical_crossentropy", optimizer="SGD", metrics = ['accuracy'])
  # print('Training ------------')
  model.fit(x_train, y_train, epochs=10, batch_size=10,verbose=0)
  # print('\nValidating ------------')
  loss, accuracy = model.evaluate(x_train, y_train,verbose=0)
  # print('validate loss: ', loss)
  print('validate accuracy: ', accuracy)
  
  return [loss,accuracy];
def model4(x_train, y_train,nperceptrons):
  model = Sequential([
    Dense(x_train.shape[0], input_dim=2,kernel_initializer=initializers.Ones()),
    Activation(activate),
    Dense(nperceptrons,kernel_initializer=initializers.Ones()),
    Activation('softmax'),
  ])
  model.compile(loss="categorical_crossentropy", optimizer="SGD", metrics = ['accuracy'])
  # print('Training ------------')
  model.fit(x_train, y_train, epochs=10, batch_size=10,verbose=0)
  # print('\nValidating ------------')
  loss, accuracy = model.evaluate(x_train, y_train,verbose=0)
  # print('validate loss: ', loss)
  print('validate accuracy: ', accuracy)
  
  return [loss,accuracy];
def model5(x_train, y_train,nperceptrons):
  model = Sequential([
    Dense(x_train.shape[0], input_dim=2,kernel_initializer=initializers.Zeros()),
    Activation(activate),
    Dense(nperceptrons,kernel_initializer=initializers.Zeros()),
    Activation('softmax'),
  ])
  model.compile(loss="categorical_crossentropy", optimizer="SGD", metrics = ['accuracy'])
  # print('Training ------------')
  model.fit(x_train, y_train, epochs=10, batch_size=10,verbose=0)
  # print('\nValidating ------------')
  loss, accuracy = model.evaluate(x_train, y_train,verbose=0)
  # print('validate loss: ', loss)
  print('validate accuracy: ', accuracy)
  
  return [loss,accuracy];
def model6(x_train, y_train,nperceptrons):
  model = Sequential([
    Dense(x_train.shape[0], input_dim=2,kernel_initializer=initializers.Constant(value=0.01)),
    Activation(activate),
    Dense(nperceptrons,kernel_initializer=initializers.Constant(value=0.01)),
    Activation('softmax'),
  ])
  model.compile(loss="categorical_crossentropy", optimizer="SGD", metrics = ['accuracy'])
  # print('Training ------------')
  model.fit(x_train, y_train, epochs=10, batch_size=10,verbose=0)
  # print('\nValidating ------------')
  loss, accuracy = model.evaluate(x_train, y_train,verbose=0)
  # print('validate loss: ', loss)
  print('validate accuracy: ', accuracy)
  
  return [loss,accuracy];
def model7(x_train, y_train,nperceptrons):
  model = Sequential([
    Dense(x_train.shape[0], input_dim=2,kernel_initializer=initializers.RandomUniform(minval=-0.05, maxval=0.05, seed=None)),
    Activation(activate),
    Dense(nperceptrons,kernel_initializer=initializers.RandomUniform(minval=-0.05, maxval=0.05, seed=None)),
    Activation('softmax'),
  ])
  model.compile(loss="categorical_crossentropy", optimizer="SGD", metrics = ['accuracy'])
  # print('Training ------------')
  model.fit(x_train, y_train, epochs=10, batch_size=10,verbose=0)
  # print('\nValidating ------------')
  loss, accuracy = model.evaluate(x_train, y_train,verbose=0)
  # print('validate loss: ', loss)
  print('validate accuracy: ', accuracy)
  
  return [loss,accuracy];

In [0]:
X_train, Y_train = x_train, y_train
Y_train2 = np_utils.to_categorical(Y_train, num_classes=nperceptrons)
[loss3,accuracy3]=model3(X_train, Y_train2,nperceptrons)
print(accuracy3)
[loss4,accuracy4]=model4(X_train, Y_train2,nperceptrons)
print(accuracy4)
[loss5,accuracy5]=model5(X_train, Y_train2,nperceptrons)
print(accuracy5)
[loss6,accuracy6]=model6(X_train, Y_train2,nperceptrons)
print(accuracy6)
[loss7,accuracy7]=model7(X_train, Y_train2,nperceptrons)
print(accuracy7)

In [29]:
X_train, Y_train = x_train, y_train
X_test, Y_test = x_test, y_test

Y_train2 = np_utils.to_categorical(Y_train, num_classes=nperceptrons)
Y_test2 = np_utils.to_categorical(Y_test, num_classes=nperceptrons)

model = Sequential([
  Dense(X_train.shape[0], input_dim=2,kernel_initializer='random_uniform',
              bias_initializer='zeros'),
  Activation(activate),
  Dense(nperceptrons,kernel_initializer='random_uniform',
              bias_initializer='zeros'),
  Activation('softmax'),
])
model.compile(loss="categorical_crossentropy", optimizer="SGD", metrics = ['accuracy'])
# print('Training ------------')
model.fit(X_train, Y_train2, epochs=10, batch_size=10,verbose=2)
# print('\nValidating ------------')
intermediate_output = model.predict(X_test)
loss, accuracy = model.evaluate(X_test, Y_test2,verbose=2)
print(intermediate_output)
# print(Y_test)
# print('validate loss: ', loss)
print('validate accuracy: ', accuracy)

Epoch 1/10
10/10 - 0s - loss: 2.5604 - accuracy: 0.6200
Epoch 2/10
10/10 - 0s - loss: 2.4496 - accuracy: 0.6700
Epoch 3/10
10/10 - 0s - loss: 2.3125 - accuracy: 0.6700
Epoch 4/10
10/10 - 0s - loss: 2.1404 - accuracy: 0.6700
Epoch 5/10
10/10 - 0s - loss: 1.9462 - accuracy: 0.6700
Epoch 6/10
10/10 - 0s - loss: 1.7600 - accuracy: 0.6700
Epoch 7/10
10/10 - 0s - loss: 1.6111 - accuracy: 0.6700
Epoch 8/10
10/10 - 0s - loss: 1.4984 - accuracy: 0.6700
Epoch 9/10
10/10 - 0s - loss: 1.4027 - accuracy: 0.6700
Epoch 10/10
10/10 - 0s - loss: 1.3128 - accuracy: 0.6700
313/313 - 0s - loss: 2.3321 - accuracy: 0.3333
[[0.06871424 0.07873537 0.19419834 ... 0.06094115 0.06418782 0.05378876]
 [0.06689934 0.07717322 0.21450461 ... 0.05934638 0.06286795 0.0519605 ]
 [0.07275002 0.08340492 0.1567548  ... 0.06312378 0.06532677 0.05828359]
 ...
 [0.06960782 0.08067847 0.18897507 ... 0.06067279 0.06363195 0.05484332]
 [0.07066392 0.08103488 0.17633297 ... 0.06197254 0.06471089 0.05594891]
 [0.0747041  0.0861569