<a href="https://colab.research.google.com/github/steven202/takehomeexam3/blob/master/exam3_question1_part3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from tensorflow.python.keras.layers import Dense, Activation
from tensorflow.python.keras import Sequential
from sklearn.datasets import make_blobs
from tensorflow.python.keras.datasets import mnist
from tensorflow.python.keras.utils import np_utils
from tensorflow.python.keras.optimizers import SGD, Adam, RMSprop
import numpy as np
from tensorflow.python.keras import initializers
from tensorflow.python.keras import initializers
from sklearn.model_selection import KFold
# http://cps.ninja/2018/09/21/keras/
# https://blog.csdn.net/marsjhao/article/details/68086225

In [0]:
np.random.seed(1337)  # for reproducibility
classes = 3; 
x_test, y_test = make_blobs(n_samples=10000, centers=classes, n_features=2)
x_train, y_train = make_blobs(n_samples=1000, centers=classes, n_features=2)

x_train = x_train.reshape(x_train.shape[0], -1)   # 标准化
x_test = x_test.reshape(x_test.shape[0], -1)
# y_train = np_utils.to_categorical(y_train, num_classes=10)
# y_test = np_utils.to_categorical(y_test, num_classes=10)

In [0]:
def model1(x_train, y_train, x_vali, y_vali,nperceptrons):
  model = Sequential([
    Dense(x_train.shape[0], input_dim=2),
    Activation('relu'),
    Dense(nperceptrons),
    Activation('softmax'),
  ])
  model.compile(loss="categorical_crossentropy", optimizer="SGD", metrics = ['accuracy'])
  # print('Training ------------')
  model.fit(x_train, y_train, epochs=10, batch_size=10,verbose=0)
  # print('\nValidating ------------')
  loss, accuracy = model.evaluate(x_vali, y_vali,verbose=0)
  # print('validate loss: ', loss)
  print('validate accuracy: ', accuracy)
  return accuracy;

In [0]:
def model2(x_train, y_train, x_vali, y_vali,nperceptrons):
  model = Sequential([
    Dense(x_train.shape[0], input_dim=2),
    Activation('sigmoid'),
    Dense(nperceptrons),
    Activation('softmax'),
  ])
  model.compile(loss="categorical_crossentropy", optimizer="SGD", metrics = ['accuracy'])
  # print('Training ------------')
  model.fit(x_train, y_train, epochs=10, batch_size=10,verbose=0)
  # print('\nValidating ------------')
  loss, accuracy = model.evaluate(x_vali, y_vali,verbose=0)
  # print('validate loss: ', loss)
  print('validate accuracy: ', accuracy)
  return accuracy;

In [0]:
#kf = KFold(n_splits=10)
kf = KFold(n_splits=10, random_state=None, shuffle=False)
errors=np.zeros((15,2));

In [0]:
for train_index, vali_index in kf.split(x_train):
  print("TRAIN:", train_index, "VALIDATE:", vali_index)
  X_train, X_vali = x_train[train_index], x_train[vali_index]
  Y_train, Y_vali = y_train[train_index], y_train[vali_index]
  for nperceptrons in range(3,15):
    Y_train2 = np_utils.to_categorical(Y_train, num_classes=nperceptrons)
    Y_vali2 = np_utils.to_categorical(Y_vali, num_classes=nperceptrons)
    errors[nperceptrons-1, 0] += model1(X_train, Y_train2, X_vali, Y_vali2,nperceptrons)
    errors[nperceptrons-1, 1] += model2(X_train, Y_train2, X_vali, Y_vali2,nperceptrons)

TRAIN: [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207
 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225
 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243
 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261
 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279
 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297
 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315
 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333
 334 335 336 337 338 339 340 341 342 343 344

In [0]:
print(errors);
error_set = errors/10;


[[ 0.          0.        ]
 [ 0.          0.        ]
 [ 9.81000012 10.        ]
 [ 9.80000013  9.98000002]
 [ 9.81000012 10.        ]
 [ 9.78000009  9.99000001]
 [ 9.80000013  9.99000001]
 [ 9.80000013  9.99000001]
 [ 9.79000008  9.98000002]
 [ 9.79000008  9.98000002]
 [ 9.80000013 10.        ]
 [ 9.81000012  9.99000001]
 [ 9.80000013  9.98000002]
 [ 9.81000012 10.        ]
 [ 0.          0.        ]]


In [0]:
accu_max = error_set[error_set != 0].max()
print(accu_max)
#https://stackoverflow.com/questions/36363163/find-index-of-min-value-in-a-matrix
ij_max = np.where(error_set == accu_max)
print(ij_max);

#ij_max = tuple([i.item() for i in ij_max])
print(ij_max);
ij_max=[3,1];
nperceptrons = ij_max[0]+1;
if ij_max[1]==0:
  activate = 'relu';
else:
  activate = 'sigmoid';

1.0
(array([ 2,  4, 10, 13]), array([1, 1, 1, 1]))
(array([ 2,  4, 10, 13]), array([1, 1, 1, 1]))


In [0]:
def model3(x_train, y_train,nperceptrons):
  model = Sequential([
    Dense(x_train.shape[0], input_dim=2,kernel_initializer='random_uniform',
                bias_initializer='zeros'),
    Activation(activate),
    Dense(nperceptrons,kernel_initializer='random_uniform',
                bias_initializer='zeros'),
    Activation('softmax'),
  ])
  model.compile(loss="categorical_crossentropy", optimizer="SGD", metrics = ['accuracy'])
  # print('Training ------------')
  model.fit(x_train, y_train, epochs=10, batch_size=10,verbose=0)
  # print('\nValidating ------------')
  loss, accuracy = model.evaluate(x_train, y_train,verbose=0)
  # print('validate loss: ', loss)
  print('validate accuracy: ', accuracy)
  
  return [loss,accuracy];
def model4(x_train, y_train,nperceptrons):
  model = Sequential([
    Dense(x_train.shape[0], input_dim=2,kernel_initializer=initializers.Ones()),
    Activation(activate),
    Dense(nperceptrons,kernel_initializer=initializers.Ones()),
    Activation('softmax'),
  ])
  model.compile(loss="categorical_crossentropy", optimizer="SGD", metrics = ['accuracy'])
  # print('Training ------------')
  model.fit(x_train, y_train, epochs=10, batch_size=10,verbose=0)
  # print('\nValidating ------------')
  loss, accuracy = model.evaluate(x_train, y_train,verbose=0)
  # print('validate loss: ', loss)
  print('validate accuracy: ', accuracy)
  
  return [loss,accuracy];
def model5(x_train, y_train,nperceptrons):
  model = Sequential([
    Dense(x_train.shape[0], input_dim=2,kernel_initializer=initializers.Zeros()),
    Activation(activate),
    Dense(nperceptrons,kernel_initializer=initializers.Zeros()),
    Activation('softmax'),
  ])
  model.compile(loss="categorical_crossentropy", optimizer="SGD", metrics = ['accuracy'])
  # print('Training ------------')
  model.fit(x_train, y_train, epochs=10, batch_size=10,verbose=0)
  # print('\nValidating ------------')
  loss, accuracy = model.evaluate(x_train, y_train,verbose=0)
  # print('validate loss: ', loss)
  print('validate accuracy: ', accuracy)
  
  return [loss,accuracy];
def model6(x_train, y_train,nperceptrons):
  model = Sequential([
    Dense(x_train.shape[0], input_dim=2,kernel_initializer=initializers.Constant(value=0.01)),
    Activation(activate),
    Dense(nperceptrons,kernel_initializer=initializers.Constant(value=0.01)),
    Activation('softmax'),
  ])
  model.compile(loss="categorical_crossentropy", optimizer="SGD", metrics = ['accuracy'])
  # print('Training ------------')
  model.fit(x_train, y_train, epochs=10, batch_size=10,verbose=0)
  # print('\nValidating ------------')
  loss, accuracy = model.evaluate(x_train, y_train,verbose=0)
  # print('validate loss: ', loss)
  print('validate accuracy: ', accuracy)
  
  return [loss,accuracy];
def model7(x_train, y_train,nperceptrons):
  model = Sequential([
    Dense(x_train.shape[0], input_dim=2,kernel_initializer=initializers.RandomUniform(minval=-0.05, maxval=0.05, seed=None)),
    Activation(activate),
    Dense(nperceptrons,kernel_initializer=initializers.RandomUniform(minval=-0.05, maxval=0.05, seed=None)),
    Activation('softmax'),
  ])
  model.compile(loss="categorical_crossentropy", optimizer="SGD", metrics = ['accuracy'])
  # print('Training ------------')
  model.fit(x_train, y_train, epochs=10, batch_size=10,verbose=0)
  # print('\nValidating ------------')
  loss, accuracy = model.evaluate(x_train, y_train,verbose=0)
  # print('validate loss: ', loss)
  print('validate accuracy: ', accuracy)
  
  return [loss,accuracy];

In [0]:
X_train, Y_train = x_train, y_train
Y_train2 = np_utils.to_categorical(Y_train, num_classes=nperceptrons)
[loss3,accuracy3]=model3(X_train, Y_train2,nperceptrons)
print(accuracy3)
[loss4,accuracy4]=model4(X_train, Y_train2,nperceptrons)
print(accuracy4)
[loss5,accuracy5]=model5(X_train, Y_train2,nperceptrons)
print(accuracy5)
[loss6,accuracy6]=model6(X_train, Y_train2,nperceptrons)
print(accuracy6)
[loss7,accuracy7]=model7(X_train, Y_train2,nperceptrons)
print(accuracy7)

validate accuracy:  0.9990000128746033
0.9990000128746033
validate accuracy:  0.6549999713897705
0.6549999713897705
validate accuracy:  0.3330000042915344
0.3330000042915344
validate accuracy:  0.33399999141693115
0.33399999141693115
validate accuracy:  0.9990000128746033
0.9990000128746033


In [0]:
X_train, Y_train = x_train, y_train
X_test, Y_test = x_test, y_test

Y_train2 = np_utils.to_categorical(Y_train, num_classes=nperceptrons)
Y_test2 = np_utils.to_categorical(Y_test, num_classes=nperceptrons)

model = Sequential([
  Dense(X_train.shape[0], input_dim=2,kernel_initializer='random_uniform',
              bias_initializer='zeros'),
  Activation(activate),
  Dense(nperceptrons,kernel_initializer='random_uniform',
              bias_initializer='zeros'),
  Activation('softmax'),
])
model.compile(loss="categorical_crossentropy", optimizer="SGD", metrics = ['accuracy'])
# print('Training ------------')
model.fit(X_train, Y_train2, epochs=10, batch_size=10,verbose=2)
# print('\nValidating ------------')
intermediate_output = model.predict(X_test)
loss, accuracy = model.evaluate(X_test, Y_test2,verbose=2)
print(intermediate_output)
# print(Y_test)
# print('validate loss: ', loss)
print('validate accuracy: ', accuracy)

Epoch 1/10
100/100 - 0s - loss: 0.9110 - accuracy: 0.5960
Epoch 2/10
100/100 - 0s - loss: 0.5852 - accuracy: 0.8270
Epoch 3/10
100/100 - 0s - loss: 0.4342 - accuracy: 0.9440
Epoch 4/10
100/100 - 0s - loss: 0.3251 - accuracy: 0.9840
Epoch 5/10
100/100 - 0s - loss: 0.2579 - accuracy: 0.9940
Epoch 6/10
100/100 - 0s - loss: 0.2092 - accuracy: 0.9960
Epoch 7/10
100/100 - 0s - loss: 0.1721 - accuracy: 0.9980
Epoch 8/10
100/100 - 0s - loss: 0.1467 - accuracy: 0.9980
Epoch 9/10
100/100 - 0s - loss: 0.1266 - accuracy: 0.9990
Epoch 10/10
100/100 - 0s - loss: 0.1116 - accuracy: 1.0000
313/313 - 0s - loss: 6.4169 - accuracy: 0.3330
[[2.4091655e-06 2.2032874e-02 9.7795677e-01 7.9082738e-06]
 [9.6625456e-07 1.6120849e-02 9.8387295e-01 5.2499818e-06]
 [3.8565115e-05 9.4039403e-02 9.0589017e-01 3.1862146e-05]
 ...
 [6.3141129e-06 4.7536071e-02 9.5244348e-01 1.4026411e-05]
 [8.9744408e-06 4.5009635e-02 9.5496595e-01 1.5511738e-05]
 [1.8844975e-04 2.2190388e-01 7.7783883e-01 6.8899091e-05]]
validate acc